# <u> Use only those concepts which have been taught till now </u>

In [1]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?

In [2]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [5]:
# Your code here
np.mean(random_integers[0:5,2:4],axis=0)

array([249834.6, 322282.4])

#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$

### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points

In [10]:
# Create the 10 points
points = np.random.randint(5,20,size=(10,2))
points

array([[18, 11],
       [10, 12],
       [10,  9],
       [11, 18],
       [ 6, 14],
       [18, 16],
       [ 6, 17],
       [ 8, 19],
       [11, 19],
       [17, 13]])

In [11]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair

Euclidean_distances = np.array([])

for x1,y1 in points:
  for x2,y2 in points:
    Euclidean_distances = np.append(Euclidean_distances,np.sqrt(((x1-x2)**2)+((y1-y2)**2)))

Euclidean_distances  = Euclidean_distances.reshape(10,10)
Euclidean_distances

array([[ 0.        ,  8.06225775,  8.24621125,  9.89949494, 12.36931688,
         5.        , 13.41640786, 12.80624847, 10.63014581,  2.23606798],
       [ 8.06225775,  0.        ,  3.        ,  6.08276253,  4.47213595,
         8.94427191,  6.40312424,  7.28010989,  7.07106781,  7.07106781],
       [ 8.24621125,  3.        ,  0.        ,  9.05538514,  6.40312424,
        10.63014581,  8.94427191, 10.19803903, 10.04987562,  8.06225775],
       [ 9.89949494,  6.08276253,  9.05538514,  0.        ,  6.40312424,
         7.28010989,  5.09901951,  3.16227766,  1.        ,  7.81024968],
       [12.36931688,  4.47213595,  6.40312424,  6.40312424,  0.        ,
        12.16552506,  3.        ,  5.38516481,  7.07106781, 11.04536102],
       [ 5.        ,  8.94427191, 10.63014581,  7.28010989, 12.16552506,
         0.        , 12.04159458, 10.44030651,  7.61577311,  3.16227766],
       [13.41640786,  6.40312424,  8.94427191,  5.09901951,  3.        ,
        12.04159458,  0.        ,  2.82842712,  5.38516481, 11.70469991],
       [12.80624847,  7.28010989, 10.19803903,  3.16227766,  5.38516481,
        10.44030651,  2.82842712,  0.        ,  3.        , 10.81665383],
       [10.63014581,  7.07106781, 10.04987562,  1.        ,  7.07106781,
         7.61577311,  5.38516481,  3.        ,  0.        ,  8.48528137],
       [ 2.23606798,  7.07106781,  8.06225775,  7.81024968, 11.04536102,
         3.16227766, 11.70469991, 10.81665383,  8.48528137,  0.        ]])

In [14]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.

Manhattan_distances = np.array([])

for x1,y1 in points:
  for x2,y2 in points:
    Manhattan_distances = np.append(Manhattan_distances,np.add(abs(x1-x2),abs(y1-y2)))

Manhattan_distances  = Manhattan_distances.reshape(10,10)
Manhattan_distances

array([[ 0.,  9., 10., 14., 15.,  5., 18., 18., 15.,  3.],
       [ 9.,  0.,  3.,  7.,  6., 12.,  9.,  9.,  8.,  8.],
       [10.,  3.,  0., 10.,  9., 15., 12., 12., 11., 11.],
       [14.,  7., 10.,  0.,  9.,  9.,  6.,  4.,  1., 11.],
       [15.,  6.,  9.,  9.,  0., 14.,  3.,  7., 10., 12.],
       [ 5., 12., 15.,  9., 14.,  0., 13., 13., 10.,  4.],
       [18.,  9., 12.,  6.,  3., 13.,  0.,  4.,  7., 15.],
       [18.,  9., 12.,  4.,  7., 13.,  4.,  0.,  3., 15.],
       [15.,  8., 11.,  1., 10., 10.,  7.,  3.,  0., 12.],
       [ 3.,  8., 11., 11., 12.,  4., 15., 15., 12.,  0.]])

## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [15]:
# Your code here
difference  = abs(Euclidean_distances - Manhattan_distances)
print(difference)
a = np.where(difference == 0)
print(len(a[0]))

[[0.         0.93774225 1.75378875 4.10050506 2.63068312 0.
  4.58359214 5.19375153 4.36985419 0.76393202]
 [0.93774225 0.         0.         0.91723747 1.52786405 3.05572809
  2.59687576 1.71989011 0.92893219 0.92893219]
 [1.75378875 0.         0.         0.94461486 2.59687576 4.36985419
  3.05572809 1.80196097 0.95012438 2.93774225]
 [4.10050506 0.91723747 0.94461486 0.         2.59687576 1.71989011
  0.90098049 0.83772234 0.         3.18975032]
 [2.63068312 1.52786405 2.59687576 2.59687576 0.         1.83447494
  0.         1.61483519 2.92893219 0.95463898]
 [0.         3.05572809 4.36985419 1.71989011 1.83447494 0.
  0.95840542 2.55969349 2.38422689 0.83772234]
 [4.58359214 2.59687576 3.05572809 0.90098049 0.         0.95840542
  0.         1.17157288 1.61483519 3.29530009]
 [5.19375153 1.71989011 1.80196097 0.83772234 1.61483519 2.55969349
  1.17157288 0.         0.         4.18334617]
 [4.36985419 0.92893219 0.95012438 0.         2.92893219 2.38422689
  1.61483519 0.         0.         3.51471863]
 [0.76393202 0.92893219 2.93774225 3.18975032 0.95463898 0.83772234
  3.29530009 4.18334617 3.51471863 0.        ]]
20

# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [ ]:
# Your code below ..

#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [ ]:
# Your function below